# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
line = "The diameter of {planet} is {diameter} kilometer."
print(line.format(planet ="Earth",diameter = 12742))

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print = (d['k1'][3]['tricky'][3]['target'][3])

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.zeros(10)*5
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
none=0
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=none)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [4]:
import pandas as pd
import numpy as np
df=pd.DataFrame(index=np.arange(3),columns=np.arange(2))
print(df)


     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [2]:
import pandas as pd
days=pd.date_range(start="1-1-2023",end="1-02-2023")
for val in days:
  print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['Tag','number'])
print(df)